export const SET_AUTHENTICATED = "SET_AUTHENTICATED";

export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";

export const SET_USER = "SET_USER";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_ERRORS = "SET_ERRORS";

export const SET_BUSINESSES = "SET_BUSINESSES";

export const SET_RESERVATIONS = "SET_RESERVATIONS";

export const SET_VALETS = "SET_VALETS";

export const SET_WALKINS = "SET_WALKINS";

export const SET_STAFFS = "SET_STAFFS";

export const POST_STAFF = "POST_STAFF";

export const STAFF_NOTWORKING = "STAFF_NOTWORKING";

export const STAFF_WORKING = "STAFF_WORKING";

export const EDIT_STAFF = "EDIT_STAFF";

export const DELET_BUSINESSES = "DELET_BUSINESSES";

export const DELETE_RESERVATIONS = "DELETE_RESERVATIONS";

export const DELETE_VALETS = "DELETE_VALETS";

export const DELETE_WALKINS = "DELETE_WALKINS";

export const POST_BUSINESS = "POST_BUSINESS";

export const POST_RESERVATION = "POST_RESERVATION";

export const POST_WALKINS = "POST_WALKINS";

export const POST_VALETS = "POST_VALETS";

export const EDIT_BUSINESS = "EDIT_BUSINESS";

export const EDIT_RESERVATION = "EDIT_RESERVATION";

export const EDIT_VALET = "EDIT_VALET";

export const EDIT_WALKIN = "EDIT_WALKIN";

export const GET_BUSINESS = "GET_BUSINESS";

export const RESERVATION_CHECKIN = "RESERVATION_CHECKIN";
export const RESERVATION_CHECKOUT = "RESERVATION_CHECKOUT";

export const GET_REQBUSINESS = "GET_REQBUSINESS";

export const DELETE_REQBUSINESS = "DELETE_REQBUSINESS";

export const WALK_OUT = "WALK_OUT";

export const VALET_TIMEOUT = "VALET_TIMEOUT";

export const GET_MENUCATEGORIES = "GET_MENUCATEGORIES";
export const EDIT_MENUCATEGORY = "EDIT_MENUCATEGORY";
export const DELETE_MENUCATEGORY = "DELETE_MENUCATEGORY";
export const POST_MENUCATEGORY = "POST_MENUCATEGORY";
export const GET_MENUCATEGORY = "GET_MENUCATEGORY";

export const GET_MENUITEMS = "GET_MENUITEMS";
export const EDIT_MENUITEM = "EDIT_MENUITEM";
export const DELETE_MENUITEM = "DELETE_MENUITEM";
export const POST_MENUITEM = "POST_MENUITEM";

export const GET_SERVICECATEGORIES = "GET_SERVICECATEGORIES";
export const EDIT_SERVICECATEGORY = "EDIT_SERVICECATEGORY";
export const DELETE_SERVICECATEGORY = "DELETE_SERVICECATEGORY";
export const POST_SERVICECATEGORY = "POST_SERVICECATEGORY";

export const GET_SERVICEITEMS = "GET_SERVICEITEMS";
export const EDIT_SERVICEITEM = "EDIT_SERVICEITEM";
export const DELETE_SERVICEITEM = "DELETE_SERVICEITEM";
export const POST_SERVICEITEM = "POST_SERVICEITEM";

export const GET_STAFFMENUCATEGORIES = "GET_STAFFMENUCATEGORIES";

export const GET_STAFFSERVICECATEGORIES = "GET_STAFFSERVICECATEGORIES";

export const SELECT_CUSTOMER = "SELECT_CUSTOMER";
export const SELECT_SERVICEITEM = "SELECT_SERVICEITEM";
export const SELECT_MENUITEM = "SELECT_MENUITEM";
export const REMOVE_SERVICEITEM = "REMOVE_SERVICEITEM";
export const REMOVE_MENUITEM = "REMOVE_MENUITEM";

export const POST_ORDER = "POST_ORDER";
export const GET_ORDERS = "GET_ORDERS";
export const GET_RESCUST = "GET_RESCUST";
export const GET_WALKCUST = "GET_WALKCUST";

export const GET_STAFFMENUITEMS = "GET_STAFFMENUITEMS";
export const GET_STAFFSERVICEITEMS = "GET_STAFFSERVICEITEMS";

export const DELETE_ORDER = "DELETE_ORDER";

export const GET_BILL = "GET_BILL";

export const MARK_PAID = "MARK_PAID";
export const ORDER_DELIVERED = "ORDER_DELIVERED";

export const GET_DELEVERD_ORDERS = "GET_DELEVERD_ORDERS";
